// Country / region scope for sector analysis. 'Global' = no geographic scope.
export const COUNTRIES = [
  'Global',
  'United States',
  'China',
  'India',
  'United Kingdom',
  'Germany',
  'France',
  'Italy',
  'Spain',
  'Netherlands',
  'Japan',
  'South Korea',
  'Singapore',
  'Indonesia',
  'Vietnam',
  'Canada',
  'Mexico',
  'Brazil',
  'Argentina',
  'Australia',
  'United Arab Emirates',
  'Saudi Arabia',
  'Israel',
  'Nigeria',
  'South Africa',
  'European Union',
  'Southeast Asia',
  'Middle East',
  'Latin America',
  'Africa',
];
